### ISSUE TITLE
Cancellative

### ISSUE THREAD

**Issue by tonyday567** [SamuelSchlesinger/Gaia#3]
How will negate, (-), cancel, lcancel & rcancel be worked in?  Will have a stab at it over the next few days if it's an open problem.

I'm not a fan of the term Cancellative at all for minus and negate,, was just categorizing.  But I'd like to get separate lcancel and rcancel's to support stripPrefix and stripSuffix-like functions.

**Comment by SamuelSchlesinger** [comment]
Yeah we can introduce things like that if you want. I'm going to push some of the new stuff I've been working on soon, it's much more piecemeal than the old stuff in a way, more composable.

**Comment by tonyday567** [comment]
I'll wait for that to be pushed then

**Comment by SamuelSchlesinger** [comment]
What do you think about this now? Is this still a concern or should I close? If we have LInvertible and RInvertible, does that mean that Invertible should be defined as:

``` Haskell

type Invertible a = (LInvertible a, RInvertible a)

```

or should it be left alone? The benefit of this is that it's more modular and coherent, but obviously that means that inv has to make the choice of being defined as linv or rinv. It just like breaks coherency of the laws that each thing should obey.
