### ISSUE TITLE
Invertible.

### ISSUE THREAD

**Issue by AnthonyJacob** [SamuelSchlesinger/Gaia#6]
A little bit of bikeshedding.

I think that`Invertible` should be called `Inversion`, otherwise `Addition` should be called `Addable`

**Comment by tonyday567** [comment]
Does that language change to a noun carry across the entire tree? Distribution? Association?

Commutative (Addition a) is short for 'a is Commutative under Addition'

However shed-like, you do get stuck with the names for a long time. So worthwhile nailing them.

**Comment by SamuelSchlesinger** [comment]
When one talks about a ring, you usually talk about its additive group and its multiplicative monoid. If anything it should change to Additive and Multiplicatives. That being said, the brevity of simply using Mul and Add is extremely alluring.

**Comment by SamuelSchlesinger** [comment]
I'm not attached to any of the names, this is an experiment more than
anything else. That being said, initiating a discussion of the notation
people like is really important if anybody is ever to want to use a
replacement for the standard Prelude.
